### ISSUE TITLE
部署到github后，网页加载异常

### ISSUE THREAD

**Issue by DreamBroke** [michaelliao/gitsite#4]
![image](https://github.com/michaelliao/gitsite/assets/17925917/e639e1da-5368-4f29-9733-b569551c0a6d)

这是我的仓库地址：https://github.com/DreamBroke/Blog

可以通过commit看到，试着启用过root-path和关闭root-path，但网页都是无法正常加载

请问是还需要做什么事才可以正常部署吗？

**Comment by michaelliao** [comment]
不绑域名，必须设置root-path

你的根路径是 https://dreambroke.github.io/Blog/，所以root-path是/Blog

root-path: /Blog
